description = "The natverse is an integrated collection of R packages designed for analysing neuroanatomical data"

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = [""]

# Define "news" as both articles and events
mainSections = ["articles", "events"]

# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"

MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"

# Logo file relative to static/images/
# to appear in upper navbar
#url = "White/071718_scivis_fly-brain_feat.jpg"
[logo]
    width = 200.85
    height = 120
    alt = "Natverse"

[footer]
    github_url = "https://github.com/natverse/"
    twitter_url = "https://twitter.com/hashtag/rstats"
    support = "Proudly supported by"

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[authors]
    show_list = "" # on list page, default is true
    show_single = "" # on single pages, default is true
    show_latest = "" # on bio, default is true
    label_latest = "" # on bio, default is "Latest"

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[events]
    link_archive = "" # default is true

# customize your site colors
# these colors get applied by layouts/partials/custom-site.css
# then, the layouts/partials/head_includes.html uses that partial
# the partial head_includes.html is called in the partial header.html everywhere!
[colors]
    text = "#1a1917" # black
    # Links
    link = "#1a9a9d"
    link_hover = "#1a9a9d"
    # Footer
    footer_primary = "#767381" # same as tidyverse.org
    footer_text = "#e3eef8" # same as tidyverse.org
    # Backgrounds
    background = "white"
    home_section_odd = "white"
    home_section_even = "#f0eee9"
    # Menu
    menu_primary = "#000000"
    menu_text = "#fff"
    menu_text_active = "#fff"
    menu_text_current = "#519199"
    menu_decorate_current = "none"
    menu_title = "#fff"
    menu_title_active = "#deef03"
    menu_box_hover = "#969696"
    menu_box_active = "white"
    # Tables
    header_background = "#dfe3eb"
    table_row_even = "#f7faff"
    table_row_odd = "#fff"
